Disable `CONFIG_CFS_BANDWIDTH` due to broken upstream backports
It's only necessary for the (optional) Docker statistics feature:
https://github.com/tomxi1997/lxc-docker-support-for-android/blob/08047ee6bffec57b13f1549846c516670fb09faa/Kconfig#L109

It fixes this:

```
/home/runner/work/Android-Kernel-Builder_mi-note-10-lite/Android-Kernel-Builder_mi-note-10-lite/VantomKernel/kernel/sched/fair.c:4890:33: error: too many arguments to function call, expected 2, have 3
 4890 |                         update_load_avg(qcfs_rq, se, 0);
      |                         ~~~~~~~~~~~~~~~              ^
/home/runner/work/Android-Kernel-Builder_mi-note-10-lite/Android-Kernel-Builder_mi-note-10-lite/VantomKernel/kernel/sched/fair.c:3695:20: note: 'update_load_avg' declared here
 3695 | static inline void update_load_avg(struct sched_entity *se, int flags)
      |                    ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Android-Kernel-Builder_mi-note-10-lite/Android-Kernel-Builder_mi-note-10-lite/VantomKernel/kernel/sched/fair.c:4891:4: error: implicit declaration of function 'se_update_runnable' [-Werror,-Wimplicit-function-declaration]
 4891 |                         se_update_runnable(se);
      |                         ^
/home/runner/work/Android-Kernel-Builder_mi-note-10-lite/Android-Kernel-Builder_mi-note-10-lite/VantomKernel/kernel/sched/fair.c:4968:32: error: too many arguments to function call, expected 2, have 3
 4968 |                         update_load_avg(cfs_rq, se, 0);
      |                         ~~~~~~~~~~~~~~~             ^
/home/runner/work/Android-Kernel-Builder_mi-note-10-lite/Android-Kernel-Builder_mi-note-10-lite/VantomKernel/kernel/sched/fair.c:3695:20: note: 'update_load_avg' declared here
 3695 | static inline void update_load_avg(struct sched_entity *se, int flags)
      |                    ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Android-Kernel-Builder_mi-note-10-lite/Android-Kernel-Builder_mi-note-10-lite/VantomKernel/kernel/sched/fair.c:4969:4: error: implicit declaration of function 'se_update_runnable' [-Werror,-Wimplicit-function-declaration]
 4969 |                         se_update_runnable(se);
      |                         ^
/home/runner/work/Android-Kernel-Builder_mi-note-10-lite/Android-Kernel-Builder_mi-note-10-lite/VantomKernel/kernel/sched/fair.c:4980:2: error: implicit declaration of function 'assert_list_leaf_cfs_rq' [-Werror,-Wimplicit-function-declaration]
 4980 |         assert_list_leaf_cfs_rq(rq);
      |         ^
```